### ISSUE TITLE
Request compat for: Minecraft Comes Alive Reborn

### ISSUE THREAD

**Issue by SpartanFischer** [TeamLapen/VampirismIntegrations#64] opened 2022-02-28 10:04 UTC
I would like to see integrations added for the mod mentioned in the title.  
I confirm it is available for the latest Minecraft version at the time of writing. The original minecraft comes alive stopped updating at 1.12, but another modder has started making a reforked version for 1.16.

## About the mod
Link to the mod page (e.g. on CurseForge): https://www.curseforge.com/minecraft/mc-mods/minecraft-comes-alive-reborn

Link to mod source/API:  https://github.com/Luke100000/minecraft-comes-alive

## What should be integrated exactly
 

Add integrations for MCA Reborn Villagers for Vampirism just like the original MCA Villagers back in 1.12. Allow players and vampires to feed on them. They would, in all aspects, behave like any other villager, having the same amount of blood, the same responses to raids from both factions, the same responses to being bitten.

## Additional comments

Thank you for taking the time to read this and for continuing your mod, it means a lot to the vampiric and hunter player base out there.

**Comment by Cheaterpaul** [comment] 2022-02-28 19:40
Duplicate of #59

**Closed as completed by Cheaterpaul** 2022-02-28 19:40 UTC
Labels: NewCompat, unconfirmed
