### ISSUE TITLE
Crashing Issue discovered with MCA.

### ISSUE THREAD

**Issue by thedeerirty** [TeamLapen/VampirismIntegrations#31] opened 2020-03-19 02:50 UTC
## Versions
- Minecraft: 1.12.2                    
- Forge: 1.12.2                       
- Vampirism: 1.6.2                
- VampirismIntegrations: 1.2.0                            

## Issue Description 
Alright, I have the mods in a modpack together, and I've encountered an error: The moment I attempt to interact with any of the MCA villagers using Vampirism (Like, biting them.) I crash. Now, this could DEFINITELY be caused by other mods, I understand that. It's just I have no issues until Vampirism interacts with MCA villagers. I'm currently using MCA 6.0.0. There is an updated version of MCA, but according to an error message I get, it isn't compatible with the current integrations. Besides the fact that it seems mostly at the fault of these two mods just by circumstance, the mod VanillaFix also highlights an issue with this mod when I crash. Sorry for troubling you with my issue.

## Reproduce Steps
I have installed the modpack RLcraft, along with these mods: https://docs.google.com/document/d/18gh2dTmBVxdS6rC7E8gvGse7hDVuagZkz_nMsOosiI0/edit?usp=sharing

To reproduce, simple try to bite a MCA villager as a vampire. 

## Additional Information
https://paste.dimdev.org/lapoxiruzo.mccrash this is a link to a crash report. I am not very bright, and there may be an entirely seperate issue causing this that is revealed in the crash report that I am too dumb to realize. If this is the case, sorry for wasting your time.

**Comment by maxanier** [comment] 2020-03-19 09:17
Thank you for reporting. This is definitively Vampirism Integrations fault.
So if you update MCA to 6.1.0 there is an error message that VampirismIntegrations does not support that version? Things should work properly with that version (in theory)

**Comment by thedeerirty** [comment] 2020-03-19 14:05
I've messed around with the 6.0.1 version and went back to 6.0.0 version due to seeming incompatible. In 6.0.1 the villagers can be bitten, and can have poison blood, but there seems to be a lack of angry and converted in that version.

However, in relation to the crash I describe, I believe I found an issue that could resolve it? While the problem still exists with me using an outdated version of MCA, I noticed when I removed the Bailey's Dailies mod that I could go back to biting and converting freely. I think, it may be an issue because that mod adds a new villager type (kinda does), and that may mess up something?

But back to the MCA, yes and error message is displayed, and most functions of the integration do not seem to work with 6.0.1. Hope this can help somehow.

**Comment by thedeerirty** [comment] 2020-03-19 15:47
I may have spoken a bit too soon on the crashing part also. I removed said mod, and installed CustomNPCs instead. I'm not engaging in and vampirism features and I randomly crash, with VanillaFix still saying it is integrations.

Latest crash report: https://paste.dimdev.org/ucizopatur.mccrash

**Comment by maxanier** [comment] 2020-03-19 18:28
Just to clarify. If you use MCA 6.**1**.0
https://www.curseforge.com/minecraft/mc-mods/minecraft-comes-alive-mca/files/2824328
the game complains that MCA is not compatible with Vampirism Integrations?

**Comment by thedeerirty** [comment] 2020-03-19 18:32
Yes, that is what it does, last I checked.

**Comment by maxanier** [comment] 2020-03-19 21:29
![mca](https://user-images.githubusercontent.com/3747729/77115712-b408d280-6a26-11ea-8c7c-3a51b93b9d1a.png)

I am sorry, but I am unable to reproduce this issue with MCA 6.1.0 and Integrations 1.2.0.
Can you please provide the full log after MC complained about incompatible versions?

About angry villagers: Yes, they are bugged in the current versions of integrations but that will be fixed

**Comment by thedeerirty** [comment] 2020-03-19 22:10
Sure thing, give me some time and I can see if I can recreate it.

**Closed as completed** 2020-11-28 15:54 UTC
